### ISSUE TITLE
Handling of `lang` [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/miniapp#100]
lang
https://w3c.github.io/miniapp/specs/manifest/#lang

> lang specifies the language tag of MiniApp. The value here takes the form of Language-Tag as defined in the [BCP47]. The default value is zh-Hans. If not specified, the default value is used. 

The English here may need further attention, since it is unclear what the "language tag of MiniApp" means. The value section should probably use some of the conformance language from BCP47.

I understand why the default value is `zh-Hans`--it is for historical reasons, due to the origins of MiniApp, but this may not make sense as a long term default. While CJK users do need the most display processing help, it might be better to say that the default value is undefined or the empty string, as this may help non-Han languages get better general performance.

Implementers should be encouraged to provide accurate language metadata and this value should match that of the manifest content.

I'd suggest this edit:

> `lang` specifies the default language of the MiniApp manifest's contents. The value here MUST be a well-formed [BCP47] language tag.

**Comment by zhangyongjing** [comment]
> lang
> https://w3c.github.io/miniapp/specs/manifest/#lang
> 
> > lang specifies the language tag of MiniApp. The value here takes the form of Language-Tag as defined in the [BCP47]. The default value is zh-Hans. If not specified, the default value is used.
> 
> The English here may need further attention, since it is unclear what the "language tag of MiniApp" means. The value section should probably use some of the conformance language from BCP47.
> 
> I understand why the default value is `zh-Hans`--it is for historical reasons, due to the origins of MiniApp, but this may not make sense as a long term default. While CJK users do need the most display processing help, it might be better to say that the default value is undefined or the empty string, as this may help non-Han languages get better general performance.
> 
> Implementers should be encouraged to provide accurate language metadata and this value should match that of the manifest content.
> 
> I'd suggest this edit:
> 
> > `lang` specifies the default language of the MiniApp manifest's contents. The value here MUST be a well-formed [BCP47] language tag.

Agreed. Thanks.

**Comment by zhangyongjing** [comment]
See update in #107

**Comment by xfq** [comment]
Since MiniApp Manifest extends Web App Manifest now, can we close this issue?

**Comment by xfq** [comment]
Closing. @aphillips Feel free to reopen if you have any concerns.
