### ISSUE TITLE
appName needs more work [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/miniapp#102]
appName
https://w3c.github.io/miniapp/specs/manifest/#appname

> appName is the name that is directly displayed to the user. It is used as the display name of MiniApp along with the desktop icon and in the context of MiniApp management. MiniApp name may be composed of Chinese characters, English letters, numbers and some special symbols, and its length must be between 4–30 characters. 

There are a number of problems with the definition here.

The length limit is defined in "characters", but this is insufficiently clear. See [CHARMOD]. I suspect that the correct definition should be "Unicode code points". 

An upper limit of 30 may be very short for some languages, particularly those that use multiple code points for a given grapheme (visual unit of text). 

The definition of the permitted list of characters is very imprecise. It is unclear which characters are meant by "Chinese characters", "English characters", "numbers", and so forth. Are specific formally defined character sets (such as GB2312, GB18030, etc.) intended? Why is there a limit here? Why not a wide range of Unicode characters? This specification limits MiniApp to a subset of languages that use (Simplified??) Chinese or ASCII.

**Comment by xfq** [comment]
Here's a link to the charmod document: https://www.w3.org/TR/charmod/

**Comment by zhangyongjing** [comment]
It's better to remove the limitation of length and character types (referring to Web App Manifest), as a harmonized standard should not put too much implementation constraints unless there is a strong reason to do that.

**Comment by zhangyongjing** [comment]
See update in #107

**Comment by zhangyongjing** [comment]
As we agreed to inherit WebApp manifest for these attributes, I believe this issue can be closed. @xfq @aphillips

**Comment by xfq** [comment]
Closing.
