### ISSUE TITLE
shortName usage [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/miniapp#103]
shortName
https://w3c.github.io/miniapp/specs/manifest/#shortname

> shortName provides a short and easy-to-read name for MiniApp, and it can be used when there is insufficient space to display the full MiniApp name provided in appName. 

The limit on `appName` is 30 "characters". This is already a short string for some languages. What is the limit on `shortName` if it is less than this? What is the character set allowed here?

When defining the length limit, bear in mind that some languages require the use of combining marks to form a "grapheme cluster" (a single visual unit of text) and that limits defined in terms of Unicode code points or UTF-16 code units may impose difficulties on these languages.

**Comment by zhangyongjing** [comment]
The proposal is to remove the limits on `appName`, and not to put limits on `shortName` either. For now, it's just a string and is up to the developer's discretion on how to populate it, unless the group find special needs to give a length or charset limitation.
See update in #107.

**Comment by zhangyongjing** [comment]
As we agreed to inherit WebApp manifest for these attributes, I believe this issue can be closed. @xfq

**Comment by xfq** [comment]
Closing.
