### ISSUE TITLE
auto value of the dir attribute?

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#115]
https://w3c.github.io/miniapp/specs/manifest/#dir

The [dir](https://www.w3.org/TR/appmanifest/#dir-member) member in Web App Manifest has an `auto` value. Do we need this?

**Comment by xfq** [comment]
See also: https://github.com/w3c/manifest/issues/923

**Comment by zhangyongjing** [comment]
This can be solved if we deiced to inherit those basic member attributes from WebApp Manifest.

**Comment by zhangyongjing** [comment]
I would suggest to support `auto` value as well since `dir` is claimed as *inherited* from WebApp manifest

**Comment by xfq** [comment]
I am neutral on this topic, but if we want to inherit from WAM, it is better to add (i.e., not to remove) the `auto` value indeed.
