### ISSUE TITLE
Spelling of "Mini App"

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#122]
We discussed the English name in https://github.com/w3c/chinese-ig/issues/152 , but didn't discuss the orthography / usage guide of the term.

Currently in our documents, there are the following usages:

* [MiniApp](https://github.com/w3c/miniapp/blob/a62ce9fbab449ac622f2d2a5a2c56430eb692686/charters/cg.html#L86)
* [MiniApps](https://github.com/w3c/miniapp/blob/a62ce9fbab449ac622f2d2a5a2c56430eb692686/charters/cg.html#L5)
* [Mini App](https://github.com/w3c/miniapp/blob/d81dd9b1676144b80692c186a82bbd1c9e571bb0/specs/manifest/docs/explainer.md#a-miniapp-manifest-comparison-with-web-app-manifest)
* [miniapp](https://github.com/w3c/miniapp/blob/b6ff6c2df2ed6ccf966fa5cef5e68fc8162f7af8/white-paper/index.html#L159)
* [miniapps](https://github.com/w3c/miniapp/blob/b6ff6c2df2ed6ccf966fa5cef5e68fc8162f7af8/white-paper/index.html#L251)
* [mini app](https://github.com/w3c/miniapp/blob/a62ce9fbab449ac622f2d2a5a2c56430eb692686/specs/uri/index.html#L98)
* [mini-app](https://github.com/w3c/miniapp/blob/a62ce9fbab449ac622f2d2a5a2c56430eb692686/white-paper/index.html#L414)

We may need to unify the usages. Not necessarily to use the same spelling/casing in all cases, but it would be useful if we define some rules/guides.

**Comment by zhangyongjing** [comment]
My two cents:
We should stick to MiniApp(s) when referring to the specific standard technology we're developing in this group. 'mini app' could be used in the context of describing a very general kind of lightweight app that may (or may not) fit the MiniApp standard. Other forms should be avoided.

**Comment by XGHeaven** [comment]
We use `Gadget` instead of `MiniApp` In Feishu/Lark. I think it better than `MiniApp`.

**Comment by espinr** [comment]
I think we can close this issue. [MiniApp](https://www.w3.org/TR/miniapp-packaging/#dfn-miniapp) is the term we are using.
