### ISSUE TITLE
Make it clear that MiniApp Manifest will be an extension of Web App Manifest

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#128]
https://w3c.github.io/miniapp/charters/wg-2020.html#deliverables

> The MiniApp Manifest specification will follow the recommendations to extend existing manifest files, provided by the Web Platform Design Principles, with the Web App Manifest as reference.

From this sentence it is not clear that MiniApp Manifest is an extension of Web App Manifest because of the phrase "as reference" (Web App Manifest may be interpreted as a general reference instead of as an extension). Can we mention that "the MiniApp Manifest specification will extend the Web App Manifest" directly?

(This issue comes from a W3C internal discussion.)

**Comment by espinr** [comment]
I think that yes, we can say that the manifest will be an extension of it. Indeed, we are refining the MiniApp Manifest draft as an extension of the Web App Manifest.

**Comment by xfq** [comment]
Fixed in #133. Closing.
