### ISSUE TITLE
[charter] In "MiniApp URI Solution", the use of URI is misleading

### ISSUE THREAD

**Issue by ylafon** [w3c/miniapp#130]
Also, linking to a document that defines an URI scheme is premature, it would be better to leave it as a new document with a goal to address the use cases pertaining to issue #34

**Comment by ylafon** [comment]
As a followup, references to DID WG in the 'Coordination' chapter is not needed, and in 4.2. Will send a PR about that and reference in 4.2

**Comment by xfq** [comment]
@ylafon Could you send a PR about that?

**Comment by xfq** [comment]
(BTW, in addition to the [draft WG charter](https://w3c.github.io/miniapp/charters/wg-2020.html), we should probably update the [CG charter](https://w3c.github.io/miniapp/charters/cg.html) and the [FAQ](https://github.com/w3c/miniapp/blob/gh-pages/docs/FAQ.md#4-why-is-there-a-need-to-create-a-new-uri-scheme-specification-how-to-use-the-new-uri-scheme-specification-to-handle-origin-how-to-handle-securecontext-without-origin-how-to-handle-cors) as well.)
