### ISSUE TITLE
[charter] Use new patent policy

### ISSUE THREAD

**Issue by frivoal** [w3c/miniapp#132]
https://w3c.github.io/miniapp/charters/wg-2020.html

Section 8 of the proposed charter refers to the old (2017) patent policy. It should be upgraded to refer to the new 2020 Patent Policy.

The only part of the text that needs to change for this is to replace
> (5 February 2004 Version updated 1 August 2017)

with
> (15 September 2020)

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/miniapp/commit/1c1b2053d0adcb9037b1f0ca59eabff2e33832b1
