### ISSUE TITLE
Is the versionCode member mandatory?

### ISSUE THREAD

**Issue by espinr** [w3c/miniapp#137]
In the MiniApp Manifest, the [versionCode](https://w3c.github.io/miniapp/specs/manifest/#dfn-versioncode) member represents the version iteration process of a mini app. It is required and it has a value (`1`) by default. 

Should we keep it as it is?

**Comment by zhangyongjing** [comment]
If you mean the default value is not necessary, I tend to agree.  But in general, it's an important attribute (more than `versionName` ) to ensure the platform compatibility and shall be checked by the miniApp hosting platform.
