### ISSUE TITLE
Seek input on accessibility user requirements.

### ISSUE THREAD

**Issue by brewerj** [w3c/miniapp#139]
https://w3c.github.io/miniapp/charters/wg-2020.html

We expect that accessibility issues will arise in the development of miniapps that could significantly impact the usability of miniapps by people with disabilities. Addressing these barriers will require more than a post-review of miniapp architecture; instead it will require pro-active early exploration of accessibility user requirements as input to the development process. 

Initial identification of accessibility user requirements for miniapps are underway. The charter modification we're requesting is simply to add a line, following the first sentence of subsection 4.1, stating 
"**The WG will seek input into accessibility user requirements."**

**Comment by xfq** [comment]
Added. Thank you.

@brewerj can you check https://w3c.github.io/miniapp/charters/wg-2020.html#coordination to see if we can close this issue?

**Comment by brewerj** [comment]
@xfq , thank you for your addition. I will indicate in the Strategy Funnel that the accessibility horizontal review is successfully completed.
