### ISSUE TITLE
Define "super-app"

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#144]
https://w3c.github.io/miniapp/white-paper/

We mentioned "super-app" a few times in the document, but didn't define or explain it.

**Comment by xfq** [comment]
Here's my two cents:

> Super apps are apps that are hosts to other apps (i.e., MiniApps) that run inside the same super app.

**Comment by espinr** [comment]
My proposal, just to avoid so many 'apps' in the definition :)

> A super app is a software platform that hosts and supports other applications (i.e., MiniApps), enabling their execution through the use of the platform's resources.
