### ISSUE TITLE
Define/Explain "UI component"

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#145]
By [@samuelweiler](https://github.com/w3c/miniapp/issues/79#issuecomment-656429590):

> "Component" is not defined well enough in the charter. (And perhaps that should be a more general comment.). Specifically: I don't understand what the term means in this context. Explain (in the charter, or by reference within the charter)?

**Comment by xfq** [comment]
I propose that we explain it by changing:

> MiniApp UI components, component-associated APIs, and a page layout template mechanism that would enhance the interoperability among different MiniApp platforms and the Web. Other components and APIs may be included by rechartering the WG scope as the incubation result from the MiniApp Community Group.

to:

> MiniApp UI components **(encapsulated reusable code for rendering a part of the UI)**, component-associated APIs, and a page layout template mechanism that would enhance the interoperability among different MiniApp platforms and the Web. Other components and APIs may be included by rechartering the WG scope as the incubation result from the MiniApp Community Group.

**Comment by xfq** [comment]
Committed in https://github.com/w3c/miniapp/commit/a4b25a42897cb0f7edd301ca15ace91fdbbddf62 . Should we close this issue?

**Comment by zhangyongjing** [comment]
sounds ok to me.

**Comment by xfq** [comment]
Closing per https://www.w3.org/2020/11/19-miniapp-minutes.html#t06
