### ISSUE TITLE
WG repo?

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#146]
If the working group is successfully formed, how do we deal with the miniapp GitHub repo? I think there are two ways: one repo and multiple repos.

The advantage of using one repo (for all the work in the CG and WG) is that there is only a single entrance and it is easy to manage. The disadvantage is the W3C IPR bot doesn't work well with this model (see https://github.com/w3c/ash-nazg/issues/181).

The advantages of using two (one for CG, one for WG) or multiple (one for each spec) are:

* Easier to handle IPR issues
* In the one-repo-for-each-spec model, if a spec is moved to another group, there's no need to set up redirect, move issues etc.

The disadvantage is that if we have too many repos, it is not easy to manage the repos.

**Comment by xfq** [comment]
Discussions in yesterday's call: https://www.w3.org/2020/12/10-miniapp-minutes.html#t03

**Comment by xfq** [comment]
These are the three options mentioned:

1. one repo for all the work in the CG and WG
2. two repos, one for CG, one for WG
3. multiple repos, one for each spec

**Comment by xfq** [comment]
I personally prefer the third option because the cost of managing IPR issues and the cost of potential transfer of the specs are the lowest. However, I will not object if the active participants in this group prefer the first or the second option.

**Comment by zhangyongjing** [comment]
I'm flexible on this issue and would be happy to follow the most common practice in W3C - what I heard is opt 3.

**Comment by xfq** [comment]
OK, I propose that we discuss this issue at this week's CG meeting, and hopefully we can reach consensus on this issue.

**Comment by Sharonzd** [comment]
Your opinions looks good to me. And we can maintain a specs list page in wg or cg.
