### ISSUE TITLE
MiniApps for IoT

### ISSUE THREAD

**Issue by QingAn** [w3c/miniapp#157]
IoT device is becoming another carrier running MiniApps. IoT MiniApp shares similar architecture of MiniApp running on the mobile. But since IoT device has different hardware capabilities with the mobile, IoT MiniApp has its unique features which we can discuss what can be incubated and standardized in W3C.

Initial thinking: some client-side APIs can be created to enable the development of MiniApps that interact with IoT device capabilities.

Some possible items:

- Bluetooth Mesh API
- Device low power management API
- UART (universal asynchronous receiver-transmitter) API
- GPIO (general-purpose input/output) API
- I2C (inter-integrated circuit) API
- SPI (serial peripheral interface) API
- ADC (analog-to-digital converter) API
- DAC (digital-to-analog converter) API
- Hardware timer API
- MQTT API

**Comment by xfq** [comment]
Related discussions:

* https://www.w3.org/2020/07/31-miniapp-minutes.html#t03
* https://www.w3.org/2020/11/19-miniapp-minutes.html#t08
* https://github.com/WebBluetoothCG/web-bluetooth/issues/445 (Bluetooth Mesh for Web Bluetooth)

**Comment by xfq** [comment]
Related work:

* [Web GPIO API](https://browserobo.github.io/WebGPIO/)
* [Web I2C API](https://browserobo.github.io/WebI2C/)

**Comment by ashimura** [comment]
@xfq asked me to respond on this issue.

I think holding joint discussions between the MiniApps WG and the Web of Things (WoT) WG/IG would make sense. So I'd suggest we start collaborative discussion, e.g., during the upcoming [WoT virtual F2F meeting (vF2F) in March](https://www.w3.org/WoT/IG/wiki/F2F_meeting,_March_2021#Virtual_F2F).

The agenda of the meeting is getting full, but I'd like to consult with the WoT Chairs if you're interested in the joint discussion there.

If it's difficult to update the agenda this time, I'd suggest we have joint discussions during the ordinary WoT calls after the March vF2F (and also TPAC vF2F) :)

**Comment by ashimura** [comment]
I talked with the WoT Chairs, and unfortunately the conclusion was it would be difficult to have a joint discussion during the WoT vF2F in March. However, we'd like to have joint discussion, e.g., during our ordinary WoT main call on Wednesday (8am Eastern) or the WoT use cases call biweekly on Tuesday (8am Eastern). @xfq , let's keep in touch and see when to have the joint call :)

**Comment by Ternence** [comment]
I found the related using case of WoT in MiniApp is These:   [WoT F2F_meeting](https://www.w3.org/WoT/IG/wiki/F2F_meeting,_March_2021#Virtual_F2F)
- MiniAPP Scripting
- Edge Computing
These are very interesting topics. It may related to SSR technology in Edge Computing or Cloud Computing. We can keeping touch.

1. Runtime level. I think the lasted MiniApp Proposal already designed OS-Based Runtime Environment. It can build or use for OS running IoT device which has user interface. But, some of IoT device is restrict devices. For its runtime environment. It may choose limited APIs or UI components for restrict devices use case. This use case was design in last MiniApp Specs.[Mini apps are applications that run on the user agent and are based on Web technology combined with native application technology. ](https://w3c.github.io/miniapp-addressing/#introduction) (this topic may have opportunities to design the general feature accessibility mechanism)

2.  APIs level:
It have use cases in nowsdays MIniApps Ecosystem. Such as Bluetooth、mDNS protocol、DLNA and IEEE 802.11 networking protocols. These API has the need of standardization to reduce the cost of MiniApp program development compatible platforms. I suggests these APIs may designed with relatied working groups in the right time.

It's my opinion.

**Comment by xfq** [comment]
Created https://github.com/w3c/miniapp-iot/ per [yesterday's meeting](https://www.w3.org/2021/06/17-miniapp-minutes.html#t01).

**Comment by espinr** [comment]
@QingAn, as I mentioned [last week](https://www.w3.org/2021/06/17-miniapp-minutes.html#t01), I was writing a document that included a use case for IoT. So I'm sharing the idea with you. The document, a [white paper on Quick Apps](https://quick-app-initiative.ow2.io/page/whitepaper/), is public now. It's about Quick Apps, but always considering Quick Apps as a concrete implementation of MiniApps. 

In the document you can find a **[case study on WoT](https://quick-app-initiative.ow2.io/page/whitepaper/#case-study-accommodation) that considers how to use the semantics of WoT to create MiniApp user interfaces**. The case is not directly related to the type of device and user agent but could be also extrapolated to any of these use cases you collected in MiniApp for IoT. 

In brief, the User Agent _understands_ the type of sensors/actuators around it, and it can render the proper user interfaces. So, the MiniApp could display `switch` buttons for turn on/off lights, a specific integer `slider` for thermostat, etc. This would provide users with:
- homogeneous interfaces in different scenarios (thermostat with the same look and feel at the office, home, or when visiting a hotel)
- accessibility features (user agent may adapt the interaction to user's preferences)
- localization of controls (thermostat in the user's preferred language and measurement units)

The [case study on WoT](https://quick-app-initiative.ow2.io/page/whitepaper/#case-study-accommodation).

**Comment by QingAn** [comment]
@espinr thanks for sharing the info. Good to know Quick Apps are also looking at the IoT case. 

From the experience of Quick Apps in IoT, do you have any suggestion to [MiniApp for IoT](https://w3c.github.io/miniapp-iot/)? We can keep discussion, and welcome for contribution.

**Comment by espinr** [comment]
I think we can close this issue. We have the ongoing document, and I included it also in the charter (#202).
