### ISSUE TITLE
XML Syntax Reference

### ISSUE THREAD

**Issue by zhangking** [w3c/miniapp#161]
XML will be  a markup language like WXML ?  WXML has Data Binding feature，like a MVVM system.  
What's the plan about XML Syntax Reference?

* https://developers.weixin.qq.com/miniprogram/en/dev/reference/wxml/

**Comment by xfq** [comment]
Looks like a duplicate of https://github.com/w3c/miniapp-packaging/issues/2

I suggest that we close this issue.

**Comment by zhangyongjing** [comment]
> Looks like a duplicate of [w3c/miniapp-packaging#2](https://github.com/w3c/miniapp-packaging/issues/2)
> 
> I suggest that we close this issue.

Agree. Let's keep the discussion in a single track.

**Comment by espinr** [comment]
Continuing the conversation in w3c/miniapp-packaging#2
