### ISSUE TITLE
The term "MiniApp"

### ISSUE THREAD

**Issue by c933103** [w3c/miniapp#18]
I have just read that initially Tencent wanted to launch mini app platform with the term "app" in their product name, but they ultimately decided against it because Apple doesn't want such a name. As such, in order to ensure the smooth development of miniapp on different operating systens including iOS, would it be better to abandon the term "miniapp" and use some other words like "mini program" which might be less objectionable?

**Comment by hax** [comment]
I remember this issue have already been discussed before, but can't find the link.

**Comment by xfq** [comment]
There was an issue on naming, although this specific issue wasn't discussed there: https://github.com/w3c/chinese-ig/issues/152

**Comment by espinr** [comment]
I think we can close this issue, since we have already included the [`MiniApp` definition](https://www.w3.org/TR/miniapp-packaging/#dfn-miniapp) and [in the White Paper](https://www.w3.org/TR/mini-app-white-paper/#what-is-miniapp).
