### ISSUE TITLE
TPAC 2022 - virtual or physical?

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#180]
Considering the risks of Covid, would you be willing to consider attending TPAC physically in 2022?   

Please use the reactions feature (screenshot below) to give a 👍 if "YES" willing to attend physically or 👎 if not and would like to meet virtually. You can also give a "😕" if you don't know.

<img width="150" alt="reactions panel screenshot" src="https://user-images.githubusercontent.com/870154/155664140-420a5417-73df-4a97-9779-3371fa703d9c.png">

Please feel free to share any thoughts or comments, like "I would only attend if X and Y were in place." Or anything that would make you comfortable attending.

**Comment by QingAn** [comment]
I think most Chinese members have difficulty in traveling to Vancouver physically. But a physical meeting might be still possible. For example, have two physical meetings in China and Vancouver and virtually connect the two physical meetings.

**Comment by xfq** [comment]
We decided not to participate in the [main TPAC 2022 event](https://www.w3.org/2022/09/TPAC/), but to participate in the TPAC 2022 China Hub instead, since most people in the WG cannot travel to Vancouver. I will open a new issue to call for agenda items.

Closing.
