### ISSUE TITLE
Capitalization of 'native app'

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#186]
'Native app' is commonly rendered in lower case ('native app'), as, for example, in:

* https://www.techtarget.com/searchsoftwarequality/definition/native-application-native-app
* https://www.app-press.com/blog/web-app-vs-native-app
* https://www.nngroup.com/articles/mobile-native-apps/

But in the [white paper](https://w3c.github.io/miniapp/white-paper/), we often use upper case ('Native App'). Should we use lower case instead?

**Comment by espinr** [comment]
I agree. I think it should be lower case. I'll do a quick review of the text and I'll PR it.

**Comment by espinr** [comment]
Closed after #187 merging
