### ISSUE TITLE
Chinese translation of "smart assistant" in the Glossary Section

### ISSUE THREAD

**Issue by sy-tang** [w3c/miniapp#19]
https://github.com/w3c/miniapp/blob/4d09d67210c6d1cb107e1d456032f7d39cbad351/white-paper/index.html#L666

Shouldn't it be "智能助理" ?

**Comment by zhangyongjing** [comment]
I propose to keep "负一屏“ since it's widely used in the Chinese context, while add "智能助理” as an alternative term to match the literal translation.

**Comment by xfq** [comment]
Fixed in #57. Closing.
