### ISSUE TITLE
typo in white paper V2

### ISSUE THREAD

**Issue by AlfredZuo** [w3c/miniapp#192]
"MiniApps can be discovered by the search engines, by search engines, MiniApp stores in the hosted app, or QR codes."

there are double "search engines" in use case 2.

**Comment by AlfredZuo** [comment]
also some syntax errors are found in the following secntences, please also handle it, thx

These Automotive MiniApps can service many user scenarios, 
it can recommend to the owner a Gas Pumping MiniApp.

**Comment by espinr** [comment]
Thanks @AlfredZuo for spotting these issues. 
I've proposed some changes in #193
