### ISSUE TITLE
MiniApp URI Scheme Draft Community Group Report  Q&A

### ISSUE THREAD

**Issue by Sharonzd** [w3c/miniapp#20]
All q&a had been recorded in [https://github.com/w3c/miniapp/blob/gh-pages/specs/uri/docs/Q&A.md](https://github.com/w3c/miniapp/blob/gh-pages/specs/uri/docs/Q&A.md)

Q1：URI 协议中暴露了下包地址，是否存在安全风险？
A1：就目前的小程序现状而言，下包地址还不是隐秘信息，通过抓包方式也会拿到下包地址， URI 的下包地址并没有增加安全风险。

Q2：为什么 URI 种需要 host 参数，需要从另外一家站点下载包吗？
A2：小程序是有这种诉求的，百度小程序目前的开源联盟就存在一个 APP 从另一个 APP 下载包的场景

Q3：["@" host [ ":" port ]]  host 是否限制？
A3：host 字段是可选的，并且值是由宿主解析的，host 可以是空值，也可以是代表某种特殊取包逻辑，比如本地调试。

Q4：location 和 dom 的 location 有关系吗？
A4：没有关系，建议宿主环境在小程序的运行时环境提供 MiniApp URI 的解析结果。

Q5：不支持小程序的浏览器访问 MiniApp URI 时会发生什么？
A5：如果不支持小程序 URI 的解析，那么通常来说，浏览器会交给系统来识别，无法识别则无响应或者提示。如果开发者希望即便是 URI 被不支持的浏览器访问，也仍然能调起小程序的话，那么建议开发者使用一些业界的通用方式，比如 deep link 的方式，调起指定 APP，从而交给能识别并能解析 MiniApp URI 的 APP 来解析。

Q6：为什么是是用 HTTPS 协议下载包？
A6：并未规定下载包，该章节只是一种实践，也可以是用其他协议下载包，或者本地取包等方式。

**Comment by xfq** [comment]
是否可以把这些问题以一个Markdown文件的形式写成一个FAQ，放到[提案的目录](https://github.com/w3c/miniapp/tree/gh-pages/specs/uri)里？

**Comment by Sharonzd** [comment]
可以的 👌
