### ISSUE TITLE
Some questions about MiniApp Lifecycle Draft Community Group Report

### ISSUE THREAD

**Issue by qianliu013** [w3c/miniapp#22]
### 是否需要在规范中明确描述如何绑定事件

目前小程序几乎都是以这种方式 `Page({onLoad(options) {...}})` 绑定的。现有的方法存在的问题是，用户事件和生命周期事件可能会冲突。

如果需要给出绑定事件的方式，那么需要考虑的因素会更多，比如 App/Page 函数是由哪个规范定义的呢？

### 是否需要在规范中明确描述事件的参数

通常的 W3C 规范，每个事件都会提供 IDL。

这样，每个事件的参数都需要仔细考虑。

一个子问题是，是否所有的事件应该也继承自一个基本事件类（类似 Event 基类）？

### 生命周期该包含什么

目前的生命周期只包含了 App.(onLaunch onShow onHide onError)，Page.(onLoad onShow onReady onHide onUnload) 这几个，而目前各个小程序厂商提供的事件都比这个多，那么容易引发问题：生命周期包含事件的标准是什么呢？

另一个小细节是，事件名是是什么？目前小程序写的 onLoad 含义应该是事件回调，所以并不是事件名，所以应该是 load；而这个与绑定事件的方式相关

### 触发时机与状态

- 规范中，首次 app.onShow page.onShow 的触发不依赖于实际的小程序/页面显示，是否合理？
- 是否应该明确描述所有的生命周期事件触发都是异步的，即只保证先后顺序，不保证是同步的？即，不保证 onLoad 执行完成后同步地执行 onShow
- 某次事件触发，对应于当前小程序的某个状态。触发回调时，除了能拿到输入参数本身，小程序开发者也能间接地感知到这种状态，如通过一些全局的获取当前上下文的 API，比如 getCurrentPages。如果考虑到这些情况，触发时机该如何说明呢？

**Comment by QingAn** [comment]
> ### 是否需要在规范中明确描述如何绑定事件
> 目前小程序几乎都是以这种方式 `Page({onLoad(options) {...}})` 绑定的。现有的方法存在的问题是，用户事件和生命周期事件可能会冲突。

目前小程序的事件绑定、生命周期都是参考了友商的产品。这点需要在标准制定过程中与业界讨论，是否需要重新定义生命周期的API，解决用户事件和生命周期事件可能会冲突的issue

或者另一种方式是，保持现有的，新的生命周期事件统一放到 events 属性中，以免和用户事件冲突。

> 
> 如果需要给出绑定事件的方式，那么需要考虑的因素会更多，比如 App/Page 函数是由哪个规范定义的呢？
> 
> ### 是否需要在规范中明确描述事件的参数
> 通常的 W3C 规范，每个事件都会提供 IDL。

同意提供IDL。如果有合适的IDL设计，欢迎提供输入

> 
> 这样，每个事件的参数都需要仔细考虑。
> 
> 一个子问题是，是否所有的事件应该也继承自一个基本事件类（类似 Event 基类）？
因为生命周期的模型没有共性，所以目前生命周期设计未用继承的方式也无法用继承的方式定义

> 
> ### 生命周期该包含什么
> 目前的生命周期只包含了 App.(onLaunch onShow onHide onError)，Page.(onLoad onShow onReady onHide onUnload) 这几个，而目前各个小程序厂商提供的事件都比这个多，那么容易引发问题：生命周期包含事件的标准是什么呢？

目前是取了最大公约数。如果有未包含的，欢迎提供内容输入

> 
> 另一个小细节是，事件名是是什么？目前小程序写的 onLoad 含义应该是事件回调，所以并不是事件名，所以应该是 load；而这个与绑定事件的方式相关

目前更新的spec，已经定义了事件名

> 
> ### 触发时机与状态
> * 规范中，首次 app.onShow page.onShow 的触发不依赖于实际的小程序/页面显示，是否合理？

app.onShow、page.onShow 主要就是监控小程序页面（应用）是否处于前台，而不是实际渲染成功或完成。小程序的逻辑和试图分别处于 worker / render 两个线程中，开发者无法直接获取 render 对象，而是通过修改 worker 上的对象，间接修改 render 展示的页面。因此开发者并不需要关心页面是否渲染完成。因此，约束实际面显示之后再执行 onShow 对开发者并不会带来什么好处，反而延迟其逻辑处理的时机。

> * 是否应该明确描述所有的生命周期事件触发都是异步的，即只保证先后顺序，不保证是同步的？即，不保证 onLoad 执行完成后同步地执行 onShow

因为 JS 是单线程的，同时生命周期回调都是不可阻塞的，也不支持返回 Promise。因此生命周期函数一定是按照顺序同步执行的。

> * 某次事件触发，对应于当前小程序的某个状态。触发回调时，除了能拿到输入参数本身，小程序开发者也能间接地感知到这种状态，如通过一些全局的获取当前上下文的 API，比如 getCurrentPages。如果考虑到这些情况，触发时机该如何说明呢？

目前还未定义这种功能的API，建议明确下场景与需求，如果产业认为有必要，可以新定义
