### ISSUE TITLE
MIME media type

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#40]
We may need a MIME media type for mini app packages.

**Comment by zhangyongjing** [comment]
We can register a MIME type like "application/miniapp-pkg"  with IANA, but such formal decision can be made during the normative work after the WG is created. In the current draft, we can put a placeholder or a NOTE giving tentative proposal (maybe using X- prefix).

**Comment by xfq** [comment]
Yeah, that could be an option. By the way, we may also need a MIME media type for the mini app manifest.

**Comment by zhangyongjing** [comment]
Do you see the case of downloading the manifest alone outside the package?

**Comment by zhangyongjing** [comment]
[PR54](https://github.com/w3c/miniapp/pull/54) is submitted

**Comment by Ternence** [comment]
This depended on the type of pkg file. If miniapp using ".zip" that it's no need for a new media type.

**Comment by zhangyongjing** [comment]
Actually, it could also be 'application/miniapp+zip' ( basically a specialized zip file.) Having the explicit '.zip' suffix allows for a generic zip parser to process the package without knowing MiniApp. No matter which way, defining a new MIME type for MiniApp package would be useful for more precise content negotiation over the network, IMHO.

**Comment by xfq** [comment]
Yes, `application/miniapp+zip` makes more sense to me.

**Comment by hax** [comment]
Did we already decide to use zip format?

**Comment by zhangyongjing** [comment]
ZIP is the current proposal. Comments are welcome.

**Comment by Ternence** [comment]
Yes, we also think about new media type. It may help for identify the miniapp files. But it not necessary in technically. 
It can be a option of HTTP implement.

**Comment by zhangyongjing** [comment]
PR #54 is updated (+zip suffix) according to the conf-call agreement today.

**Comment by xfq** [comment]
Closing.
