### ISSUE TITLE
Add privacy and security considerations to the manifest spec

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#48]
We need a privacy and security considerations section.

References:

* https://www.w3.org/TR/appmanifest/#installation-sec
* https://www.w3.org/TR/appmanifest/#navigation-scope-security-considerations
* https://www.w3.org/TR/appmanifest/#security-and-privacy-considerations
* https://www.w3.org/TR/appmanifest/#media-type-registration

**Comment by xfq** [comment]
Also, web app manifest seems to use CSP. Do we want to use it as well?

**Comment by xfq** [comment]
#50 added a Security and Privacy Considerations section.

**Comment by zhangyongjing** [comment]
Should we close it? @xfq

**Comment by xfq** [comment]
Yes. We can file new issues when needed.
