### ISSUE TITLE
Do we really need 'app' as the root folder?

### ISSUE THREAD

**Issue by zhangyongjing** [w3c/miniapp#56]
The MiniApp package can just contain the files (and subfolders) at the root level directly, without the need of an wrapper folder 'app'.  Can we simply remove the 'app' folder?

**Comment by qianliu013** [comment]
:raising_hand:

**Comment by xfq** [comment]
In [today's CG call](https://www.w3.org/2020/05/14-miniapp-minutes.html) we decided to remove the `app` directory.

**Comment by zhangyongjing** [comment]
will cover this change in the updated PR#55

**Comment by zhangyongjing** [comment]
done in PR#55.
