### ISSUE TITLE
Unicode support for appName

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#59]
https://w3c.github.io/miniapp/specs/manifest/#appname

> MiniApp name may be composed of Chinese characters, English letters, numbers and some specific symbols

Is there any reason for not allowing other Unicode code points (except for the code points that must be escaped, like quotation mark or reverse solidus)?

-----

Edited to add another point:

> and its length must be between 4–30 characters.

If we want to limit the length, I would suggest that we explicit mention the type of unit we limit (i.e., Unicode code points). "Character" is a very vague term, and one "character" is not always one Unicode code point.

**Comment by zhangyongjing** [comment]
I think that was a starting point from some existing implementations. We could relax it a bit to be more generic, e.g. just a 'string'. Any other thoughts?

**Comment by xfq** [comment]
Related i18n WG comment: https://github.com/w3c/miniapp/issues/102

**Comment by zhangyongjing** [comment]
As we decided to inherit member attributes from WebApp Manfiest, `appName` would be replaced by `name` and the problem shall be solved accordingly. @xfq

**Comment by xfq** [comment]
Yes. We can close this when https://github.com/w3c/miniapp/pull/136 is merged.

**Comment by xfq** [comment]
Closing.
