### ISSUE TITLE
i18n review

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#61]
Following i18n WG [ACTION-911](https://www.w3.org/International/track/actions/911), I'm filing this issue to track the status of our i18n review. I'll create the review request issues as separate issues and link to them in this issue.

**Comment by xfq** [comment]
Link to the review requests:

* [URI Scheme](https://github.com/w3c/i18n-request/issues/117)
* [Manifest](https://github.com/w3c/i18n-request/issues/118)

**Comment by zhangyongjing** [comment]
i18n support in 'package' is proposed as pr #85
