### ISSUE TITLE
Default value for lang in the manifest spec

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#62]
https://w3c.github.io/miniapp/specs/manifest/#lang

> lang specifies the language tag of MiniApp. The value of lang here takes the value of Language-Tag defined in the [BCP47]; please see more details in locales. Default is zh-CN.

`zh-CN` is an old tag for Chinese used in Mainland China, and should be avoided if possible. I recommend that we use `zh-Hans` instead (which stands for Simplified Chinese and uses the script subtag instead of the region subtag).

**Comment by zhangyongjing** [comment]
I agree. Even I'm think if it's better not to mention the default value since we're going to globalize our spec.

**Comment by xfq** [comment]
> Even I'm thinking if it's better not to mention the default value since we're going to globalize our spec.

That makes sense. We still need a default value tho, like `undefined`.

**Comment by zhangyongjing** [comment]
Making the default value as `undefined` seems strange, since it's not syntactically correrct. I'd rather have it as `zh-Hans` if a default value is a must. Is it a must?

**Comment by xfq** [comment]
I mean, we need to specify the behavior when the value of `lang` is empty or an invalid BCP 47 tag. It could be "undefined", which means the primary language for the manifest is unknown, or some specific language (like `zh-Hans` or `en`).

**Comment by zhangyongjing** [comment]
OK. I can do an update later.

**Comment by zhangyongjing** [comment]
done in PR#70. @xfq 
https://github.com/w3c/miniapp/pull/70/commits/7ad31b9942f7bb3136db4b1f7b2813899a1e9e97

**Comment by zhangyongjing** [comment]
Can we close this issue now? @xfq

**Comment by xfq** [comment]
I think we can close this issue when https://github.com/w3c/miniapp/pull/136 is merged.
