### ISSUE TITLE
[charter]: suggest to use positive words

### ISSUE THREAD

**Issue by zhangyongjing** [w3c/miniapp#68]
in the current draft charter 'success criteria': "APIs that cannot be demonstrated to be implementable securely will not be released." 

How about changing it to: "APIs shall be demonstrated to be implementable securely before released"

**Comment by zhangyongjing** [comment]
see update in #83

**Comment by zhiqiangyu** [comment]
agree. it looks better to me.

**Comment by xfq** [comment]
#83 has been merged. Closing.
