### ISSUE TITLE
Charter: expand WebAppSec citation?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/miniapp#77]
>  The Web Application Security Working Group is developing guidance on APIs that expose sensitive information, and an API to manage permissions, both of which matter to this group's specifications. 

I'm not entirely sure what is intended by this, particularly the first part, and I encourage you to expand on it.

**Comment by xfq** [comment]
The MiniApp Manifest has a [reqPermissions](https://w3c.github.io/miniapp/specs/manifest/#reqpermissions) array which may be relevant to some of the work in WebAppSec. Some potential deliverables like device APIs (see also #79) may also be relevant.
