### ISSUE TITLE
Explain what super/host app is and why we need it

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#78]
https://w3c.github.io/miniapp/charters/wg-2020.html

> To enhance the interoperability between different MiniApp platforms (AKA the super application or host application)

It would be useful to add a sentence or two to explain how super/host app is different from the browsers and why.

**Comment by zhangyongjing** [comment]
see update in #83

**Comment by xfq** [comment]
Related meta issue: https://github.com/w3c/miniapp/issues/89

**Comment by xfq** [comment]
Closing given that #83 has been merged. Further discussions can happen in #89 or new issues.
