### ISSUE TITLE
Mention EPUB 3 WG in the Coordination section of the charter

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#84]
https://w3c.github.io/miniapp/charters/wg-2020.html#coordination

We should add EPUB 3 WG in the Coordination section of the charter to ensure our [packaging spec](https://w3c.github.io/miniapp/specs/packaging/) is consistent with EPUB's [OCF packaging](https://www.w3.org/publishing/epub32/epub-ocf.html) when possible.

Note that the EPUB 3 WG has not been created yet, so we can add it later (when it is created). Here's some background Information:

* [W3C strategy funnel issue](https://github.com/w3c/strategy/issues/217)
* [EPUB 3 WG charter proposal](https://w3c.github.io/epub-3-wg-charter/)
* [Blog post that outlines the background of the EPUB work](https://www.w3.org/blog/2020/03/listen-to-the-people-the-future-of-epub-and-new-directions-for-publishing-w3c/)

**Comment by zhangyongjing** [comment]
We can coordinate with EPUB 3 and absorb useful designing techniques, but I would disagree with the intention to 'be consistent with' the OCF spec. The purpose are totally different. There are many other packaging formats developed based on ZIP, I don't think we have the obligation to align ourselves with all of them. Efforts should be spent when it makes more senses.

**Comment by xfq** [comment]
I may not have made my point clear, sorry. What I meant was that if there are existing wheels in OCF that are useful for MiniApp packages, we can learn from or reuse them rather than creating a brand new one. I didn't mean that the package structure/metadata of OCF and MiniApp need to be very similar. Does that address your concern?

**Comment by zhangyongjing** [comment]
OK. That's clear now.

**Comment by xfq** [comment]
Yesterday's meeting minutes: https://www.w3.org/2020/06/18-miniapp-minutes.html#t13

**Comment by xfq** [comment]
Closing per https://www.w3.org/2020/07/09-miniapp-minutes.html#t02
