### ISSUE TITLE
TAG review

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#86]
This issue tracks the status of our TAG review.

**Comment by xfq** [comment]
Link to the review requests:

* [URI Scheme](https://github.com/w3ctag/design-reviews/issues/478)

**Comment by zhangyongjing** [comment]
> Link to the review requests:
> 
> * [URI Scheme](https://github.com/w3ctag/design-reviews/issues/478)
> * [Lifecycle](https://github.com/w3ctag/design-reviews/issues/523)

*[Manifest](https://github.com/w3ctag/design-reviews/issues/524)

@xfq

**Comment by xfq** [comment]
Thanks @zhangyongjing!
