### ISSUE TITLE
Web App Manifest compatibility

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp#94]
Should we rename `appName` and `shortName` to `name` and `short_name` to be compatible with Web App Manifest?

We might also want to consider using snake case instead of camel case for other attributes.

Differences of the two formats: https://github.com/w3c/miniapp/blob/gh-pages/specs/manifest/docs/explainer.md#4-relationship-with-web-app-manifest

**Comment by zhangyongjing** [comment]
That's do-able. We should have group consensus before moving forward. And this naming convension should be consistent across all specs within MiniApp.

**Comment by xfq** [comment]
Another way is to make MiniApp Manifest an extension or a fork of the Web App Manifest, but I'm not sure if it's technically feasible.

**Comment by cynthia** [comment]
Fork is undesirable. If anything it should probably be an extension (for those specific to this) or all merged upstream to WAM.

**Comment by zhangyongjing** [comment]
We can do mapping/mirroring, but folking can be problematic due to dependency issues.

**Comment by xfq** [comment]
> folking can be problematic due to dependency issues

According to my understanding, forking is the way to solve the dependency issue. We can remove the dependency on HTML/CSP, for example. (I'm not saying that forking is a correct solution, I just provided some ideas for us to discuss.)

**Comment by xfq** [comment]
See #119 for a proposal to rewrite the spec based on Web App Manifest.

**Comment by xfq** [comment]
Related discussions last week: https://www.w3.org/2020/08/26-manifest-minutes.html

**Comment by espinr** [comment]
As discussed during the [Meeting on Manifest (26 Aug)](https://www.w3.org/2020/08/26-manifest-minutes.html), the MiniApp Manifest should be an extension of the [WebApp Manifest](https://www.w3.org/TR/appmanifest/). Since there is an extension mechanism already defined in the WebApp Manifest, the MiniApp Manifest may be implemented using the [extension point](https://www.w3.org/TR/appmanifest/#extensibility).

**Comment by xfq** [comment]
To summarize the discussions in the [Meeting on Manifest (26 Aug)](https://www.w3.org/2020/08/26-manifest-minutes.html), it would be beneficial to:

* Use the Web App Manifest as the base format, since all properties in Web App Manifest are optional. Indicate which Web App Manifest properties are relevant, the set of restrictions applied to the values (such as only using local URLs for the pages). When backward compatibilities is needed, indicate so and recommend using duplicate values (the frameworks can make that transparent).

* For properties that are specific to MiniApp, consider using a prefix or add them to a `miniapp` property to avoid future compatibility issues. For each MiniApp-specific property, consider raising an issue against the Web App manifest specification for future adoption in Web App manifest (such as the properties supported under `window`).

* For permissions, consider re-using the same features used by `document.featurePolicy.features()`, e.g., "geolocation", "gamepad", "magnetometer", "accelerometer", "xr-spatial-tracking", "picture-in-picture", "camera", "payment", "pointer-lock", etc. Again, a prefix may be used for MiniApp specific features.

**Comment by espinr** [comment]
Thanks, @xfq. 

Just as a reference, this is the [compilation of the standardized policy features](https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#standardized-features).

**Comment by xfq** [comment]
Closing as #136 has been merged.
