### ISSUE TITLE
Direction metadata discussion [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/miniapp#99]
dir
https://w3c.github.io/miniapp/specs/manifest/#dir

> dir specifies the base direction of the text value of the app name, short name and description members. The value of dir can be ltr or rtl. ltr means from left to right, rtl means from right to left. Default: ltr. 

This section looks okay on its surface, but I would suggest some editorial tweaking on the English, as well as noting the previous concern about a single attribute for all NL values.

**Comment by xfq** [comment]
Can you give some specific suggestions to the text, Addison?

**Comment by xfq** [comment]
Since MiniApp Manifest extends Web App Manifest now, can we close this issue?

**Comment by xfq** [comment]
Closing per i18n WG meeting.
